### PR TITLE
Minor fix (CalledProcessError exception)

### PR DESCRIPTION
**Pull request by stasinopoulos**

### CODE REVIEW

**Comment by stamparm** [comment]
I see what you did here. Removing space after class definition was :D

Committed slightly better version. Nevertheless, thank you for submitting an Issue/Pull Request

**Comment by stasinopoulos** [comment]
Hmm the problem with the https://github.com/stamparm/DSVW/commit/75d15a4917b4a53dad7a04b1f97fa801f69c6c68 fix is that, if someone puts an attack vector :

```
http://192.168.2.11:65412/?domain=;echo$(ls)
```

the application loops ... forever.

**Comment by stamparm** [comment]
1) your proposition suffers from this too. Just checked
2) i am not sure that "damn vulnerable" should support this kind of stuff, especially if its a corner case (I wouldn't ever run something like `echo $(ls)` against the arbitrary execution vulnerability)
3) application is not in `loops ... forever` mode. Its single thread is in stale mode
4) opening a new window and trying to connect to the dsvw will work without any problems
5) i'll try to find a solution, even for `echo $(ls)`

**Comment by stamparm** [comment]
`domain=;echo$(ls)` waits because nslookup enters into the interactive shell mode (because of lack of arguments). will try to find a way how to circumvent this

**Comment by stamparm** [comment]
@stasinopoulos now you example works too. thank you for your report

**Comment by stasinopoulos** [comment]
Yeap @stamparm! I confirm that it works like a charm. :)

**Pull request closed without merging**
